"""Reproducible local ITBench-AA campaigns: download, prepare, run, report."""

import argparse
import ast
import asyncio
import csv
import fcntl
import json
import platform
import re
import sys
import time
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path

from .bench_data import (
    PILOT,
    REPO,
    REVISION,
    TITLE,
    EvidenceIndex,
    atomic_json,
    confined,
    create_index,
    dumps,
    file_hash,
    fingerprint,
    snapshot_files,
    upgrade_index,
)
from .bench_ledger import PRICE_NANODOLLARS_PER_TOKEN, REQUEST_CEILING, Ledger
from .bench_score import score
from .config import Application, Configuration
from .diagnostics import failure_details
from .models import RawIncident

DEFAULT_DATASET = Path.home() / "Projects/ITBench-AA"
DEFAULT_ROOT = Path(".local/itbench-aa-prepared-v2")
DEFAULTS = {
    "model": "jev-1.13.0",
    "calls": None,
    "incident_seconds": 1800,
    "tool_seconds": 15,
    "decision_timeout_seconds": None,
    "attempt_timeout_seconds": 30.0,
    "identical_attempts": 1,
    "freshness_seconds": 600,
    "budget_usd": None,
    "memory_bytes": 8192,
    "max_retries": 2,
    "retry_initial_seconds": 0.5,
    "retry_max_seconds": 5,
    "probability_sum_tolerance": 0.02,
    "strict_probabilities": False,
    "allow_model_escalation": False,
    "assessments": False,
    "escalation_penalty": 1.0,
    "requests_per_second": 80,
    "tokens_per_second": 100000,
    "entity_page": 12,
    "candidates": 20,
    "evidence_bytes": 4096,
    "index_version": 2,
    "state_bytes": 8192,
    "seeds": [42, 43, 44],
    "pilot": PILOT,
}
METHOD_DIFFERENCES = [
    "Only the 40 public snapshots are evaluated; AA also evaluates 19 private cases.",
    "Jev selects one closed-set action per round; no shell, SQL, arbitrary paths, generated tool arguments or fallback model. HTTP 408/429/5xx and transport failures permit two exponential-backoff retries within any aggregate and incident deadline, matching TypeSafe SDK defaults; malformed responses are not retried.",
    "The benchmark uses the native returned choice, following the official TypeSafe SDK parser. All options must be present and probability values finite and in [0,1]. Near-one sums within 0.02 are proportionally normalized. Other sum deviations and disagreement between the returned choice and probability ranking are diagnostic warnings; raw probabilities and the unchanged native choice remain recorded. Unknown choices, malformed schemas, invalid numeric ranges and model mismatches remain fatal. SDK reference revision: f078f1e208a0d885154dc758344ae4fce77ac168.",
    "Deterministic entity/filter matching and observed workload ownership replace AA's model-based normalization. Service/Pod equivalence requires explicit ground-truth aliases; named chaos-mesh Schedule objects use AA's documented spawned-resource rule.",
    "The malformed leading-wildcard filter '*.*' in the pinned release's scenario 38 is mechanically repaired to regex '.*.*'; repairs are recorded in each scoring artifact. Identical duplicate group definitions are merged while preserving root-cause flags.",
    "Evidence pages are limited to 4 KiB and the current investigation to 8 KiB; complete sanitized evidence remains in indexes and original file/record references.",
    "Candidate ordering uses seeds 42, 43, 44; entities are browsed 12 at a time, starting with causal public-alert targets and their observed dependency neighborhood, then application and chaos namespaces. Informational alerts retain evidence but do not seed the causal shortlist.",
    "Optional narrow Choice/Noul/Score assessments share accounting, retries and rate admission; state is capped at 8 KiB and batches at six questions. Cached opinions rank presentation and populate hypotheses; they do not authorize nominations or force submission.",
    "Reasoning and evidence strings are generated by code from selected reason categories and inspected records.",
    "A resolved Dowser outcome means a structurally valid submission completed. Root-cause correctness is scored after termination and never enters another decision round.",
    "SOM selects investigation, recall, nomination, submission or wait. Model-selected escalation is disabled by default in the benchmark profile; operational failure stops remain active. Optional exit penalties are explicit policy adjustments to SOM scores, preserve native decisions for audit, and are not calibrated model probabilities. SQLite supplies bounded cumulative evidence and outcomes. Semantic repetition checks exclude transient revisions. A 30-minute incident watchdog reports incomplete execution; tool/HTTP attempt deadlines are 15/30 seconds; the incident deadline bounds decisions. No call-count or monetary ceiling is imposed. Every HTTP attempt reserves 64,000 input tokens for accounting; unknown billed outcomes retain that reservation. Account caps remain 80 requests/s and 100,000 tokens/s.",
    "Client admission enforces the user's account caps of 80 requests and 100,000 tokens per rolling second across trial/provider construction and retries. Rate reservations use the 64,000-token input ceiling plus 2,048 output tokens of headroom, reconciled to reported input-plus-output usage. Rate waits share any aggregate and incident deadline; pricing reservations remain independent and durable.",
]


def transient_full_failure(row):
    detail = row.get("failure", {})
    status = detail.get("http_status", 0)
    if row.get("category") == "provider" and detail.get("code") in {
        "provider_deadline",
        "deadline_exceeded",
        "request_cancelled",
    }:
        return True
    return (
        row.get("category") == "provider"
        and detail.get("retryable", False)
        and (
            detail.get("category") == "transport"
            or status in {408, 429}
            or 500 <= status < 600
        )
    )


def normalize_report_row(row):
    """Correct old trim/escalation labels without rewriting paid trial records."""
    if (
        row.get("category") == "context"
        and (row.get("terminal") or {}).get("reason") == "Jev selected escalation"
        and not row.get("failure")
        and not row.get("error_type")
    ):
        return {**row, "recorded_category": "context", "category": "abandoned"}
    return row


def runner_execution_fingerprint(source):
    """Only batch management and reporting can change on an approved resume."""
    management = {
        "run_campaign",
        "main",
        "report",
        "transient_full_failure",
        "runner_execution_fingerprint",
        "record_runner_update",
        "failure_category",
        "normalize_report_row",
    }
    nodes = []
    for node in ast.parse(source).body:
        if (
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name in management
        ):
            continue
        if isinstance(node, ast.Import) and all(
            alias.name == "ast" for alias in node.names
        ):
            continue
        nodes.append(ast.dump(node, include_attributes=False))
    return fingerprint(nodes)


def record_runner_update(campaign, existing, expected, base, authorized):
    before, after = existing["code_hashes"], expected["code_hashes"]
    if set(before) != set(after) or any(
        before[k] != after[k] for k in before if k != "dowser/bench.py"
    ):
        raise ValueError("execution code changed; new campaign required")
    revisions = existing.get("runner_revisions", [])
    if revisions and revisions[-1]["sha256"] == after["dowser/bench.py"]:
        return
    if not authorized:
        raise ValueError("runner update must be explicitly recorded on resume")
    original = confined(campaign, "source/dowser/bench.py")
    current = base / "dowser/bench.py"
    if file_hash(original) != before["dowser/bench.py"] or runner_execution_fingerprint(
        original.read_text()
    ) != runner_execution_fingerprint(current.read_text()):
        raise ValueError("per-trial execution changed; new campaign required")
    source = campaign / "runner-revisions" / (after["dowser/bench.py"] + ".py")
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_bytes(current.read_bytes())
    revisions.append(
        {
            "recorded_at": datetime.now(UTC).isoformat(),
            "sha256": after["dowser/bench.py"],
            "source": str(source),
            "reason": "Batch management or reporting correction without replay; per-trial execution, scoring, configuration and budgets are unchanged. Completed paid trial records are reused.",
        }
    )
    existing["runner_revisions"] = revisions
    existing["batch_policy"] = {
        "continue_transient_full_failures": True,
        "continue_transient_pilot_failures": True,
        "cooldown_seconds": 60,
    }
    note = "Exhausted transient upstream failures in full-run trials retain zero scores and all spending reservations; the batch continues after a 60-second cooldown without replay. Other technical failures still halt."
    if note not in existing["methodological_differences"]:
        existing["methodological_differences"].append(note)
    pilot_note = "User-authorized pilot continuation retains exhausted transient provider failures with zero score and advances after a 60-second cooldown without replay. Permanent provider, schema and execution failures still halt. Full-run admission remains separately gated."
    if pilot_note not in existing["methodological_differences"]:
        existing["methodological_differences"].append(pilot_note)
    atomic_json(campaign / "manifest.json", existing)


def read_json(path):
    return json.loads(confined(Path(path).parent, Path(path).name).read_text())


def download(dataset):
    from huggingface_hub import HfApi, snapshot_download

    dataset = Path(dataset).absolute()
    if dataset.is_symlink():
        raise ValueError("dataset symlink forbidden")
    files = HfApi(token=False).list_repo_files(
        REPO, repo_type="dataset", revision=REVISION
    )
    snapshot_download(
        REPO,
        repo_type="dataset",
        revision=REVISION,
        local_dir=dataset,
        token=False,
        max_workers=4,
    )
    atomic_json(
        dataset / ".dowser-download.json",
        {"repository": REPO, "revision": REVISION, "files": sorted(files)},
    )
    print(f"Downloaded {len(files)} files at {REVISION}", flush=True)


def prepare(dataset, root, source_indexes=None):
    import yaml

    dataset, root = Path(dataset).absolute(), Path(root).absolute()
    receipt = read_json(dataset / ".dowser-download.json")
    if receipt["revision"] != REVISION or receipt["repository"] != REPO:
        raise ValueError("dataset revision mismatch")
    # Require every remotely enumerated file before indexing or paid calls.
    hashes = {}
    for relative in receipt["files"]:
        path = confined(dataset, relative)
        hashes[relative] = file_hash(path)
        path.chmod(0o444)
    scenarios = sorted(
        {
            int(p.split("/")[1].removeprefix("Scenario-"))
            for p in hashes
            if p.startswith("sre/Scenario-")
        }
    )
    if len(scenarios) != 40 or not set(PILOT) <= set(scenarios):
        raise ValueError("expected 40 public scenarios and fixed pilot")
    license_text = confined(dataset, "README.md").read_text()
    if "cc-by-4.0" not in license_text:
        raise ValueError("dataset license not verified")
    indexes = {}
    for scenario in scenarios:
        name = f"Scenario-{scenario}"
        gt = yaml.safe_load(
            confined(dataset, f"sre/{name}/ground_truth.yaml").read_text()
        )
        score(gt, {"contributing_factors": []}, [])  # validate both GT layouts
        output = root / "indexes" / f"{name}.sqlite3"
        expected = {
            p.removeprefix(f"sre/{name}/"): h
            for p, h in hashes.items()
            if p.startswith(f"sre/{name}/")
        }
        if output.exists():
            index = EvidenceIndex(output, scenario)
            if any(expected.get(p) != h for p, h in index.meta["files"].items()):
                raise ValueError("existing index differs from dataset")
            meta = index.meta
            coverage = {
                relative for _, relative, _ in snapshot_files(dataset / "sre" / name)
            }
            if set(meta["files"]) != coverage or meta["version"] != 2:
                raise ValueError(
                    "existing index has old coverage or schema; prepare in a separate root"
                )
        else:
            if source_indexes is not None:
                evidence_files = {
                    relative
                    for _, relative, _ in snapshot_files(dataset / "sre" / name)
                }
                meta = upgrade_index(
                    confined(Path(source_indexes), f"{name}.sqlite3"),
                    output,
                    scenario,
                    {k: v for k, v in expected.items() if k in evidence_files},
                )
            else:
                meta = create_index(dataset / "sre" / name, output, scenario)
            output.chmod(0o444)
        indexes[name] = {**meta, "path": str(output), "sha256": file_hash(output)}
        print(f"Prepared {name}: {meta['counts']}", flush=True)
    metadata = {
        "repository": REPO,
        "revision": REVISION,
        "license": "CC-BY-4.0",
        "dataset": str(dataset),
        "files": hashes,
        "scenarios": scenarios,
        "indexes": indexes,
    }
    metadata["fingerprint"] = fingerprint(metadata)
    atomic_json(root / "prepared.json", metadata)
    return metadata


def code_metadata(base):
    paths = [
        *base.glob("dowser/*.py"),
        *base.glob("plugins/*.py"),
        base / "pyproject.toml",
    ]
    return {p.relative_to(base).as_posix(): file_hash(p) for p in sorted(paths)}


def campaign_manifest(prepared, base):
    return {
        "title": TITLE,
        "created_at": datetime.now(UTC).isoformat(),
        "dataset_fingerprint": prepared["fingerprint"],
        "dataset_revision": REVISION,
        "dataset_license": prepared["license"],
        "dataset_file_hashes": prepared["files"],
        "index_hashes": {k: v["sha256"] for k, v in prepared["indexes"].items()},
        "python": platform.python_version(),
        "dependency_lock_sha256": file_hash(base / "uv.lock"),
        "code_hashes": code_metadata(base),
        "configuration": DEFAULTS,
        "pricing": {
            "input_nanodollars_per_token": PRICE_NANODOLLARS_PER_TOKEN,
            "output_nanodollars_per_token": 0,
            "request_token_ceiling": REQUEST_CEILING,
            "source": "https://docs.typesafe.ai/models",
            "verified_at": datetime.now(UTC).isoformat(),
        },
        "methodological_differences": METHOD_DIFFERENCES,
        "sources": [
            "https://huggingface.co/datasets/ArtificialAnalysis/ITBench-AA",
            "https://artificialanalysis.ai/methodology/intelligence-benchmarking#itbench-aa",
            "https://arxiv.org/abs/2502.05352",
            "https://github.com/typesafe-ai/typesafe-sdk-python/blob/f078f1e208a0d885154dc758344ae4fce77ac168/src/typesafe_sdk/_core/response_types.py",
            "https://github.com/typesafe-ai/typesafe-sdk-python/blob/f078f1e208a0d885154dc758344ae4fce77ac168/src/typesafe_sdk/_core/retry.py",
        ],
    }


def freeze_price_source(directory):
    import urllib.request

    price_doc = (
        urllib.request.urlopen("https://docs.typesafe.ai/models.md", timeout=15)
        .read()
        .decode()
    )
    if (
        "0.042" not in price_doc
        or "64k tokens per request" not in price_doc
        or "Output tokens are free" not in price_doc
    ):
        raise ValueError(
            "current price/ceiling differs; update accounting before paid execution"
        )
    (directory / "pricing-source.md").write_text(price_doc)
    return file_hash(directory / "pricing-source.md")


def archive_sources(directory, base, hashes):
    for relative, sha in hashes.items():
        original = base / relative
        if file_hash(original) != sha:
            raise ValueError("source changed before archival")
        archived = directory / "source" / relative
        archived.parent.mkdir(parents=True, exist_ok=True)
        archived.write_bytes(original.read_bytes())
        if file_hash(archived) != sha:
            raise ValueError("source changed during archival")


def trial_config(campaign, prepared, scenario, trial, seed):
    index = prepared["indexes"][f"Scenario-{scenario}"]["path"]
    settings = {
        "index": index,
        "scenario": scenario,
        "trial": trial,
        "output": str(campaign / "diagnoses" / (trial + ".json")),
        "seed": seed,
        "allow_escalation": DEFAULTS["allow_model_escalation"],
    }
    return Configuration.model_validate(
        {
            "limits": {
                "incident_seconds": DEFAULTS["incident_seconds"],
                "tool_seconds": 15,
                "identical_attempts": DEFAULTS["identical_attempts"],
                "changes": 1,
                "freshness_seconds": 600,
            },
            "event_store": {
                "factory": "dowser.store:sqlite_store",
                "settings": {"path": str(campaign / "history.sqlite3")},
            },
            "tool_registry": {
                "factory": "dowser.core:tool_registry",
                "settings": {
                    "plugins": [
                        {
                            "factory": "plugins.itbench_aa:tool_plugin",
                            "settings": settings,
                        }
                    ]
                },
            },
            "normalizer": {
                "factory": "plugins.itbench_aa:normalizer",
                "settings": settings,
            },
            "context_builder": {
                "factory": "dowser.core:context_builder",
                "settings": {
                    "recent_outcomes": 4,
                    "memory_bytes": DEFAULTS["memory_bytes"],
                },
            },
            "decision_provider": {
                "factory": "plugins.itbench_aa:decision_provider",
                "settings": {
                    "ledger": str(campaign / "spending.sqlite3"),
                    "trial": trial,
                    "assessments": DEFAULTS["assessments"],
                    "model": "jev-1.13.0",
                    "decision_timeout_seconds": DEFAULTS["decision_timeout_seconds"],
                    "attempt_timeout_seconds": DEFAULTS["attempt_timeout_seconds"],
                    "max_retries": DEFAULTS["max_retries"],
                    "retry_initial_seconds": DEFAULTS["retry_initial_seconds"],
                    "retry_max_seconds": float(DEFAULTS["retry_max_seconds"]),
                    "probability_sum_tolerance": DEFAULTS["probability_sum_tolerance"],
                    "strict_probabilities": DEFAULTS["strict_probabilities"],
                    "allow_escalation": DEFAULTS["allow_model_escalation"],
                    "escalation_policy": {
                        "factory": "plugins.escalation:escalation_policy",
                        "settings": {
                            "enabled": DEFAULTS["allow_model_escalation"],
                            "penalty": DEFAULTS["escalation_penalty"],
                        },
                    },
                    "requests_per_second": DEFAULTS["requests_per_second"],
                    "tokens_per_second": DEFAULTS["tokens_per_second"],
                },
            },
            "validation_policy": {
                "factory": "dowser.core:validation_policy",
                "settings": {
                    "allow_changes": True,
                    "allowed_resources": [f"Scenario-{scenario}"],
                },
            },
            "executor": {"factory": "dowser.core:executor"},
            "verifier": {"factory": "dowser.core:verifier"},
            "incident_loop": {
                "factory": "dowser.loop:incident_loop",
                "settings": {
                    "bounded_runtime_view": True,
                    "batch_diagnostics": True,
                    "profile": True,
                },
            },
        }
    )


def failure_category(events, terminal, ledger, trial):
    if terminal and terminal["outcome"] == "resolved":
        return "completed"
    if (
        ledger.call_limit is not None
        and ledger.stats(trial)["calls"] >= ledger.call_limit
    ):
        return "call_limit"
    if ledger.last_error(trial) == "SpendingLimit" or any(
        e["kind"] == "provider_failure"
        and e["payload"].get("error_type") == "SpendingLimit"
        for e in events
    ):
        return "budget"
    if terminal and any(
        marker in terminal["reason"]
        for marker in (
            "required incident context exceeds",
            "context builder made no progress",
            "context builder did not reduce",
        )
    ):
        return "context"
    if any(e["kind"] == "provider_failure" for e in events):
        return "provider"
    if any(
        e["kind"] == "runtime_failure"
        and e["payload"].get("error_type") == "ContextOverflowError"
        for e in events
    ):
        return "context"
    if any(
        e["kind"] == "parse_outcome" and e["payload"]["parse"]["status"] != "valid"
        for e in events
    ):
        return "parsing"
    if any(e["kind"] == "runtime_failure" for e in events):
        return "runtime"
    if any(
        e["kind"] == "verification" and e["payload"]["status"] == "failed"
        for e in events
    ):
        return "submission"
    if terminal and "deadline" in terminal["reason"]:
        return "deadline"
    if terminal and "submission" in terminal["reason"]:
        return "submission"
    return "abandoned" if terminal else "interrupted"


async def run_trial(campaign, prepared, scenario, trial, seed, phase, base):
    path = campaign / "trials" / (trial + ".json")
    output = campaign / "diagnoses" / (trial + ".json")
    ledger = Ledger(campaign / "spending.sqlite3")
    events = []
    if path.exists():
        recorded = read_json(path)
        if recorded["dataset_fingerprint"] != prepared["fingerprint"] or recorded[
            "configuration_fingerprint"
        ] != fingerprint(DEFAULTS):
            raise ValueError("trial resume fingerprint mismatch")
        if recorded["status"] == "completed":
            return recorded
        # Never automatically replay an interrupted incident. A durable submission
        # can be validated and scored without another call to Jev.
        if output.exists():
            from plugins.itbench_aa import Plugin, Settings

            from .contracts import AppContext
            from .models import Limits
            from .store import SQLiteStore

            store = SQLiteStore(campaign / "history.sqlite3")
            try:
                state = await store.reconstruct(trial)
                from plugins.itbench_aa import working

                plugin = Plugin(
                    Settings(
                        index=prepared["indexes"][f"Scenario-{scenario}"]["path"],
                        scenario=scenario,
                        trial=trial,
                        output=str(output),
                        seed=seed,
                    ),
                    AppContext({"event_store": store}, Limits(), base),
                )
                plugin.revision = working(state)["revision"]
                await plugin.candidates(state)
                # If interruption occurred after writing but before parse admission,
                # the previous nomination state still determines the same output.
                if read_json(output) != plugin.diagnosis(working(state)["nominations"]):
                    raise ValueError("durable submission fails ownership validation")
                recorded["submission_completed"] = True
                recorded["category"] = "interrupted_with_submission"
            finally:
                await store.aclose()
        else:
            recorded["submission_completed"] = False
            recorded["category"] = "interrupted"
        recorded["status"] = "completed"
    else:
        recorded = {
            "trial": trial,
            "scenario": scenario,
            "seed": seed,
            "phase": phase,
            "status": "running",
            "dataset_fingerprint": prepared["fingerprint"],
            "configuration_fingerprint": fingerprint(DEFAULTS),
            "started_at": datetime.now(UTC).isoformat(),
        }
        atomic_json(path, recorded)
        started = time.monotonic()
        events, terminal = [], None
        try:
            async with Application(
                trial_config(campaign, prepared, scenario, trial, seed), base
            ) as app:
                raw = RawIncident(
                    source_id="itbench-aa",
                    event_id=trial,
                    payload={"scenario": scenario, "trial": trial},
                )
                state = await app.services["normalizer"].normalize(raw)
                result = await app.services["incident_loop"].run(state)
                terminal = result.model_dump(mode="json")
                events = [
                    e.model_dump(mode="json")
                    for e in await app.services["event_store"].history(trial)
                ]
        except (KeyboardInterrupt, asyncio.CancelledError):
            recorded.update(
                category="interrupted", duration_seconds=time.monotonic() - started
            )
            atomic_json(path, recorded)
            raise
        except Exception as error:
            recorded["error_type"] = type(error).__name__
            recorded["failure"] = failure_details(error)
            if (campaign / "history.sqlite3").exists():
                from .store import SQLiteStore

                store = SQLiteStore(campaign / "history.sqlite3")
                try:
                    events = [
                        e.model_dump(mode="json") for e in await store.history(trial)
                    ]
                    terminal = next(
                        (
                            e["payload"]
                            for e in reversed(events)
                            if e["kind"] == "terminated"
                        ),
                        None,
                    )
                except KeyError:
                    pass
                finally:
                    await store.aclose()
        recorded.update(
            status="completed",
            terminal=terminal,
            submission_completed=bool(
                terminal and terminal["outcome"] == "resolved" and output.exists()
            ),
            category=failure_category(events, terminal, ledger, trial),
            duration_seconds=time.monotonic() - started,
        )
        if recorded.get("error_type") and recorded["category"] in {
            "abandoned",
            "interrupted",
        }:
            recorded["category"] = "runtime"
        if recorded.get("error_type") == "ContextOverflowError":
            recorded["category"] = "context"
    recorded.update(ledger.stats(trial))
    reads, recalled, keys = 0, 0, []
    decisions, navigation, unchanged_decisions = [], [], []
    semantic_findings = set()
    semantic_repeats = 0
    omitted_facts = 0
    for event in events:
        if event["kind"] == "provider_request":
            omitted_facts = max(
                omitted_facts,
                event["payload"]["request"]
                .get("memory", {})
                .get("progress", {})
                .get("omitted_facts", 0),
            )
        if event["kind"] == "parse_outcome":
            for fact in event["payload"]["parse"].get("memory_facts", []):
                value = fact["payload"]
                if value.get("meaningful"):
                    findings = {
                        (value.get("entity"), fp)
                        for fp in value.get("semantic_fingerprints", [])
                    }
                    semantic_repeats += int(
                        bool(findings) and findings <= semantic_findings
                    )
                    semantic_findings.update(findings)
        if event["kind"] != "execution_started":
            continue
        args = event["payload"].get("candidate", {}).get("args", {})
        operation = args.get("operation")
        identity = event["payload"].get("identity", {})
        decisions.append(identity.get("key", dumps(args)))
        unchanged_decisions.append(dumps(identity))
        if operation in {"browse", "focus", "recall"}:
            navigation.append(identity.get("key", dumps(args)))
        recalled += int(operation == "recall")
        if operation in {"inspect", "next"}:
            reads += 1
            keys.append(
                dumps(
                    [
                        args.get(k)
                        for k in ("scenario", "entity", "kind", "offset", "segment")
                    ]
                )
            )
    recorded.update(
        external_evidence_reads=reads,
        recalled_evidence_pages=recalled,
        repeated_external_reads=reads - len(set(keys)),
        repeated_decisions=len(decisions) - len(set(decisions)),
        unchanged_repeated_decisions=len(unchanged_decisions)
        - len(set(unchanged_decisions)),
        navigation_cycles=len(navigation) - len(set(navigation)),
        semantic_novelty=len(semantic_findings),
        semantic_repeats=semantic_repeats,
        omitted_facts=omitted_facts,
        provider_timings=ledger.timings(trial),
    )
    recorded["failure_details"] = ledger.diagnostics(trial)
    recorded["response_adjustments"] = sum(
        len(
            e["payload"]["result"]
            .get("score_metadata", {})
            .get("response_adjustments", [])
        )
        for e in events
        if e["kind"] == "provider_result"
    )
    terminal_failure = next(
        (
            e["payload"]["failure"]
            for e in reversed(events)
            if e["kind"] in {"provider_failure", "runtime_failure"}
            and "failure" in e["payload"]
        ),
        None,
    )
    if terminal_failure:
        recorded["failure"] = terminal_failure
    if recorded["category"] != "completed" and (
        recorded.get("failure") or recorded["failure_details"]
    ):
        print(
            dumps(
                {
                    "kind": "trial_failure",
                    "trial": trial,
                    "category": recorded["category"],
                    "failure": recorded.get("failure")
                    or recorded["failure_details"][-1]["failure"],
                }
            ),
            file=sys.stderr,
            flush=True,
        )
    import yaml

    gt = yaml.safe_load(
        confined(
            Path(prepared["dataset"]), f"sre/Scenario-{scenario}/ground_truth.yaml"
        ).read_text()
    )
    index = EvidenceIndex(prepared["indexes"][f"Scenario-{scenario}"]["path"], scenario)
    diagnosis = (
        read_json(output)
        if recorded["submission_completed"]
        else {"contributing_factors": []}
    )
    scoring = score(gt, diagnosis, index.entities(), index.relationships())
    if not recorded["submission_completed"]:
        scoring.update(score=0.0, exact_root_set=False)
    atomic_json(campaign / "scoring" / (trial + ".json"), scoring)
    recorded.update(
        score=scoring["score"],
        exact_root_set=scoring["exact_root_set"],
        finished_at=datetime.now(UTC).isoformat(),
    )
    atomic_json(path, recorded)
    return recorded


def report(campaign):
    campaign = Path(campaign).absolute()
    manifest = read_json(campaign / "manifest.json")
    records = [
        normalize_report_row(read_json(p))
        for p in sorted((campaign / "trials").glob("*.json"))
    ]
    completed = [r for r in records if r["status"] == "completed"]
    full = [r for r in completed if r["phase"] == "full"]
    pilot = [r for r in completed if r["phase"] == "pilot"]
    spending = Ledger(campaign / "spending.sqlite3")
    ledger = spending.stats()
    diagnostics = spending.diagnostics()
    with (campaign / "diagnostics.jsonl").open("w") as handle:
        for detail in diagnostics:
            handle.write(dumps(detail) + "\n")
    summary = {
        "title": TITLE,
        "full_trials": len(full),
        "expected_full_trials": 120,
        "pilot_trials": len(pilot),
        "mean_score": sum(r["score"] for r in full) / len(full) if full else None,
        "exact_root_set_accuracy": sum(r["exact_root_set"] for r in full) / len(full)
        if full
        else None,
        "failure_categories": dict(Counter(r["category"] for r in full)),
        "pilot_categories": dict(Counter(r["category"] for r in pilot)),
        "pilot_mean_score": sum(r["score"] for r in pilot) / len(pilot)
        if pilot
        else None,
        "duration_seconds": sum(r.get("duration_seconds", 0) for r in completed),
        "ledger": ledger,
        "failure_codes": dict(Counter(d["failure"]["code"] for d in diagnostics)),
        "budget_usd": ledger["budget_nanodollars"] / 1e9
        if ledger["budget_nanodollars"] is not None
        else None,
        "response_adjustments": sum(
            r.get("response_adjustments", 0) for r in completed
        ),
        "accounted_cost_usd": ledger["accounted_nanodollars"] / 1e9,
        "complete": len(full) == 120 and len(pilot) == 10,
        "pilot_finished": len(pilot) == 10,
        "pilot_exact_root_set_accuracy": sum(r["exact_root_set"] for r in pilot)
        / len(pilot)
        if pilot
        else None,
        "incomplete_executions": sum(
            r["category"] not in {"completed", "abandoned"} for r in completed
        ),
        "external_evidence_reads": sum(
            r.get("external_evidence_reads", 0) for r in completed
        ),
        "recalled_evidence_pages": sum(
            r.get("recalled_evidence_pages", 0) for r in completed
        ),
        "repeated_external_reads": sum(
            r.get("repeated_external_reads", 0) for r in completed
        ),
    }
    for metric in (
        "repeated_decisions",
        "unchanged_repeated_decisions",
        "navigation_cycles",
        "semantic_novelty",
        "semantic_repeats",
        "omitted_facts",
    ):
        summary[metric] = sum(r.get(metric, 0) for r in completed)
    atomic_json(campaign / "summary.json", summary)
    with (campaign / "results.jsonl").open("w") as handle:
        for row in completed:
            handle.write(dumps(row) + "\n")
    fields = [
        "trial",
        "phase",
        "scenario",
        "seed",
        "category",
        "submission_completed",
        "score",
        "exact_root_set",
        "calls",
        "input_tokens",
        "output_tokens",
        "accounted_nanodollars",
        "unknown_calls",
        "model_latency_seconds",
        "duration_seconds",
        "response_adjustments",
        "external_evidence_reads",
        "recalled_evidence_pages",
        "repeated_external_reads",
        "repeated_decisions",
        "unchanged_repeated_decisions",
        "navigation_cycles",
        "semantic_novelty",
        "semantic_repeats",
        "omitted_facts",
    ]
    with (campaign / "results.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(completed)
    lines = [
        f"# {TITLE}",
        "",
        f"Campaign: `{campaign.name}`. Full trials: **{len(full)}/120**; pilot trials: **{len(pilot)}/10**.",
        "",
        f"Mean full-run precision at full recall: **{summary['mean_score']}**. Exact root-set accuracy: **{summary['exact_root_set_accuracy']}**.",
        "",
        f"Pilot mean: {summary['pilot_mean_score']} (kept separate). Full failure categories: `{dumps(summary['failure_categories'])}`. Pilot categories: `{dumps(summary['pilot_categories'])}`.",
        f"Pilot exact accuracy: {summary['pilot_exact_root_set_accuracy']}. Incomplete executions: {summary['incomplete_executions']}. External evidence reads: {summary['external_evidence_reads']}; repeated unchanged external reads: {summary['repeated_external_reads']}; recalled pages: {summary['recalled_evidence_pages']}.",
        "",
        f"Model: `{manifest['configuration']['model']}`. Calls: {ledger['calls']}. Input/output tokens: {ledger['input_tokens']}/{ledger['output_tokens']}. Accounted cost including unknown reservations: **${summary['accounted_cost_usd']:.6f}**. Spending ceiling: {('$' + str(summary['budget_usd'])) if summary['budget_usd'] is not None else 'none'}. Unknown calls: {ledger['unknown_calls']}.",
        "",
        f"Prior campaign accounted cost: ${ledger['prior_accounted_nanodollars'] / 1e9:.9f}; prior calls: {ledger['prior_calls']}; prior unknown calls: {ledger['prior_unknown_calls']}. Retry attempts in this campaign: {ledger['retry_calls']}. Structured failures: `{dumps(summary['failure_codes'])}`; attempt details are in `diagnostics.jsonl` and the ledger.",
        "",
        f"Provider score diagnostics (renormalizations and consistency warnings): {summary['response_adjustments']}; raw and normalized probabilities and adjustment details are preserved in history.sqlite3.",
        "",
        f"Cumulative model latency: {ledger['model_latency_seconds']:.3f}s. Total trial duration: {summary['duration_seconds']:.3f}s.",
        "",
        f"Dataset revision: `{manifest['dataset_revision']}`; license: {manifest['dataset_license']}; Python: {manifest['python']}; lock SHA-256: `{manifest['dependency_lock_sha256']}`.",
        "",
        "All dataset and code hashes, configuration, price, and methodological differences are in `manifest.json`. Individual histories are in `history.sqlite3`; submissions, scoring, trial records, and the durable spending ledger are adjacent. Results are exported as `results.jsonl` and `results.csv`.",
        "",
        "## Methodological differences",
        "",
        *[f"- {s}" for s in manifest["methodological_differences"]],
        "",
        "## Sources",
        "",
        *[f"- {s}" for s in manifest["sources"]],
    ]
    (campaign / "summary.md").write_text("\n".join(lines) + "\n")
    return summary


async def run_campaign(
    root,
    campaign_id,
    *,
    phase="all",
    base=None,
    previous_campaign=None,
    resume_runner_update=False,
    continue_interrupted=False,
):
    if continue_interrupted and phase != "pilot":
        raise ValueError("interrupted-case continuation is restricted to pilot phase")
    base = Path(base or Path.cwd()).absolute()
    root = Path(root).absolute()
    prepared = read_json(root / "prepared.json")
    if (
        fingerprint({k: v for k, v in prepared.items() if k != "fingerprint"})
        != prepared["fingerprint"]
    ):
        raise ValueError("prepared manifest fingerprint mismatch")
    if not re.fullmatch(r"[A-Za-z0-9_-]+", campaign_id):
        raise ValueError("invalid campaign ID")
    campaign = root / campaign_id
    campaign.mkdir(parents=True, exist_ok=True)
    with confined(campaign, "campaign.lock", must_exist=False).open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        manifest_path = campaign / "manifest.json"
        if previous_campaign is None and manifest_path.exists():
            previous = read_json(manifest_path).get("previous_campaign")
        else:
            previous = (
                Ledger.prior_snapshot(
                    Path(previous_campaign).absolute() / "spending.sqlite3"
                )
                if previous_campaign
                else None
            )
        if previous and Path(previous["path"]).parent == campaign:
            raise ValueError("campaign cannot inherit its own spending")
        if previous and Ledger.prior_snapshot(Path(previous["path"])) != previous:
            raise ValueError("previous campaign spending changed")
        expected = campaign_manifest(prepared, base)
        expected["previous_campaign"] = previous
        if (campaign / "manifest.json").exists():
            existing = read_json(campaign / "manifest.json")
            for key in [
                "dataset_fingerprint",
                "dependency_lock_sha256",
                "configuration",
                "python",
                "previous_campaign",
            ]:
                if existing[key] != expected[key]:
                    raise ValueError("campaign resume fingerprint mismatch")
            if existing["code_hashes"] != expected["code_hashes"]:
                record_runner_update(
                    campaign, existing, expected, base, resume_runner_update
                )
        else:
            # Freeze a fresh copy of the price source before any paid call and
            # verify the documented rate/ceiling rather than trusting a constant.
            expected["pricing"]["source_sha256"] = freeze_price_source(campaign)
            archive_sources(campaign, base, expected["code_hashes"])
            atomic_json(campaign / "manifest.json", expected)
        if continue_interrupted:
            manifest = read_json(manifest_path)
            manifest.setdefault("batch_policy", {})[
                "continue_interrupted_pilot_cases"
            ] = True
            note = "Explicit user-authorized continuation retains interrupted pilot cases and their costs without replay, then runs untouched cases. These interrupted executions remain reported separately. Full evaluation is not started."
            if note not in manifest["methodological_differences"]:
                manifest["methodological_differences"].append(note)
            atomic_json(manifest_path, manifest)
        # Verify immutable snapshot and index hashes before paid execution.
        for relative, sha in prepared["files"].items():
            if file_hash(confined(Path(prepared["dataset"]), relative)) != sha:
                raise ValueError("dataset changed after preparation")
        for meta in prepared["indexes"].values():
            if (
                file_hash(confined(Path(meta["path"]).parent, Path(meta["path"]).name))
                != meta["sha256"]
            ):
                raise ValueError("evidence index changed after preparation")
        # Exercise the initial normalizer/candidate/context boundary for every
        # scenario before spending anything, including missing evidence types.
        from plugins.itbench_aa import Normalizer, Plugin, Settings
        from plugins.jev import JevProvider, JevSettings

        from .contracts import AppContext
        from .models import DecisionRequest, Limits

        preflight = []
        for scenario in prepared["scenarios"]:
            settings = Settings(
                index=prepared["indexes"][f"Scenario-{scenario}"]["path"],
                scenario=scenario,
                trial="preflight",
                output=str(campaign / "diagnoses" / "preflight.json"),
            )
            context = AppContext({}, Limits(), base)
            state = await Normalizer(settings, context).normalize(
                RawIncident(
                    source_id="itbench-aa",
                    event_id="preflight",
                    payload={"scenario": scenario, "trial": "preflight"},
                )
            )
            candidates = await Plugin(settings, context).candidates(state)
            check = await JevProvider(JevSettings(), context).check_context(
                DecisionRequest(
                    incident_id="preflight", state=state, candidates=candidates
                )
            )
            if not check.fits:
                raise ValueError("scenario preflight context overflow")
            preflight.append(
                {"scenario": scenario, "context": check.model_dump(mode="json")}
            )
        atomic_json(campaign / "preflight.json", preflight)
        campaign_ledger = Ledger(
            campaign / "spending.sqlite3", budget=None, call_limit=None
        )
        if previous:
            campaign_ledger.inherit(previous)
        if phase in {"all", "pilot"}:
            for scenario in PILOT:
                row = await run_trial(
                    campaign,
                    prepared,
                    scenario,
                    f"pilot-s{scenario}",
                    42,
                    "pilot",
                    base,
                )
                row = normalize_report_row(row)
                print(
                    f"{row['trial']}: {row['category']}, score={row['score']}, calls={row['calls']}",
                    flush=True,
                )
                report(campaign)
                if continue_interrupted and row["category"] in {
                    "interrupted",
                    "interrupted_with_submission",
                }:
                    print(
                        "Interrupted pilot result and costs retained without replay; advancing to untouched cases.",
                        flush=True,
                    )
                    continue
                if transient_full_failure(row):
                    print(
                        "Transient pilot failure retained with zero score; no replay. Cooling down for 60 seconds before advancing.",
                        flush=True,
                    )
                    await asyncio.sleep(60)
                    continue
                if row["category"] not in {
                    "completed",
                    "abandoned",
                    "call_limit",
                    "deadline",
                }:
                    print(
                        "Pilot technical failure recorded; correction required before continuing.",
                        flush=True,
                    )
                    return campaign
            failures = [
                normalize_report_row(
                    read_json(campaign / "trials" / f"pilot-s{s}.json")
                )
                for s in PILOT
            ]
            if any(
                r["category"]
                not in {"completed", "abandoned", "call_limit", "deadline"}
                and not transient_full_failure(r)
                and not (
                    continue_interrupted
                    and r["category"] in {"interrupted", "interrupted_with_submission"}
                )
                for r in failures
            ):
                print(
                    "Pilot technical checks failed; full evaluation has not started.",
                    flush=True,
                )
                return campaign
        if phase in {"all", "full"}:
            pilot = [
                normalize_report_row(
                    read_json(campaign / "trials" / f"pilot-s{s}.json")
                )
                for s in PILOT
            ]
            if any(
                r["status"] != "completed"
                or r["category"]
                not in {"completed", "abandoned", "call_limit", "deadline"}
                for r in pilot
            ):
                raise ValueError(
                    "ten-case pilot technical checks required before full run"
                )
            for repeat, seed in enumerate([42, 43, 44], 1):
                for scenario in prepared["scenarios"]:
                    ledger = Ledger(campaign / "spending.sqlite3")
                    if ledger.budget is not None and (
                        ledger.stats()["accounted_nanodollars"]
                        + REQUEST_CEILING * PRICE_NANODOLLARS_PER_TOKEN
                        > ledger.budget
                    ):
                        print(
                            "Campaign budget exhausted before next trial.", flush=True
                        )
                        return campaign
                    row = await run_trial(
                        campaign,
                        prepared,
                        scenario,
                        f"full-r{repeat}-s{scenario}",
                        seed,
                        "full",
                        base,
                    )
                    print(
                        f"{row['trial']}: {row['category']}, score={row['score']}, calls={row['calls']}",
                        flush=True,
                    )
                    report(campaign)
                    if transient_full_failure(row):
                        print(
                            "Transient upstream failure retained with zero score; no replay. Cooling down for 60 seconds before continuing.",
                            flush=True,
                        )
                        await asyncio.sleep(60)
                        continue
                    if row["category"] in {
                        "provider",
                        "parsing",
                        "context",
                        "submission",
                        "runtime",
                        "interrupted",
                    }:
                        print(
                            "Technical failure recorded; correction required before continuing.",
                            flush=True,
                        )
                        return campaign
        report(campaign)
    return campaign


def main(argv=None):
    parser = argparse.ArgumentParser(description=TITLE)
    subs = parser.add_subparsers(dest="command", required=True)
    for name in ["download", "prepare", "run", "report"]:
        sub = subs.add_parser(name)
        if name in {"download", "prepare"}:
            sub.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
        if name in {"prepare", "run"}:
            sub.add_argument("--root", type=Path, default=DEFAULT_ROOT)
        if name == "prepare":
            sub.add_argument(
                "--source-indexes",
                type=Path,
                help="Copy matching sanitized indexes into a separate versioned preparation root",
            )
        if name == "run":
            sub.add_argument(
                "--assessments",
                action="store_true",
                help="Use narrow SOM assessments for presentation and hypotheses",
            )
            sub.add_argument(
                "--campaign", default=datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
            )
            sub.add_argument("--phase", choices=["all", "pilot", "full"], default="all")
            sub.add_argument(
                "--allow-model-escalation",
                action="store_true",
                help="Offer voluntary escalation to the SOM (disabled by default)",
            )
            sub.add_argument(
                "--escalation-penalty",
                type=float,
                default=1.0,
                help="Exit penalty >=1; higher discourages escalation; requires --allow-model-escalation",
            )
            sub.add_argument(
                "--previous-campaign",
                type=Path,
                help="Carry forward its cumulative accounted spending",
            )
            sub.add_argument(
                "--resume-runner-update",
                action="store_true",
                help="Record an archived batch-only code revision before continuing an existing campaign",
            )
            sub.add_argument(
                "--continue-interrupted",
                action="store_true",
                help="Retain interrupted pilot cases without replay and advance to untouched cases (pilot phase only)",
            )
        if name == "report":
            sub.add_argument("campaign", type=Path)
    args = parser.parse_args(argv)
    try:
        if args.command == "download":
            download(args.dataset)
        elif args.command == "prepare":
            prepare(args.dataset, args.root, args.source_indexes)
        elif args.command == "run":
            DEFAULTS["assessments"] = args.assessments
            from plugins.escalation import Settings as EscalationSettings

            controls = EscalationSettings(
                enabled=args.allow_model_escalation, penalty=args.escalation_penalty
            )
            if controls.penalty != 1 and not controls.enabled:
                parser.error("--escalation-penalty requires --allow-model-escalation")
            DEFAULTS.update(
                allow_model_escalation=controls.enabled,
                escalation_penalty=controls.penalty,
            )
            campaign = asyncio.run(
                run_campaign(
                    args.root,
                    args.campaign,
                    phase=args.phase,
                    previous_campaign=args.previous_campaign,
                    resume_runner_update=args.resume_runner_update,
                    continue_interrupted=args.continue_interrupted,
                )
            )
            print(campaign)
            summary = report(campaign)
            if args.phase in {"all", "full"} and not summary["complete"]:
                return 2
        else:
            print(json.dumps(report(args.campaign), indent=2))
    except (KeyboardInterrupt, asyncio.CancelledError):
        print("Interrupted; durable trials and reservations retained.", file=sys.stderr)
        return 130
    except Exception as error:
        # Never display arbitrary exception text from credentials or data.
        print(
            dumps({"kind": "benchmark_failure", "failure": failure_details(error)}),
            file=sys.stderr,
            flush=True,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
